version: '3'

####### VOLUMES  #######
volumes:  
  caddy:
    driver: local
  node:
    driver: local

services:
   node:
    image: ${APP_NAME}-node:1.0
    container_name: ${APP_NAME}-node
    build: 
      context: ./node      
    environment: 
        - HOST=0.0.0.0        
    command: yarn dev
    volumes:
      - ${APP_PATH}/:/var/www
    ports:
      - 3000:3000